# Generated by Django 4.2.30 on 2026-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_sevabooking_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sevabooking',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
